travis:
  secure:
    BINSTAR_TOKEN: mZ52xQrSdKsvLDJHwBlEQeQV76ok6LdtOlqkeaizM3guFBFxuy/rq/WmnNv7I3Pjo8gz7p1TN1cRIS9fNxd/4ZL0bnSqkcJUxibwwgUGc6OhkX+fIFTdZpZQfvAKvKQA+PnAR6aFd8vmuQNor2QLLeVcnLOw9l0lyhEJDQGpIQPZFwJjytmSGYG8WA+Czr+1YDKdPNEsKmyoVBIrrOADNbzpLuSMC8G/kob4n00WUpbiVp9BabF/VZiRjiTukvx14CCuQsOkBv7TzwgkmNTlcnLjPDyCX7zawOTbCTIoAtI8/e3RAPh764zqu2RPm6WZl4QI3OldvCYAyNtVPcyLE9q2IliLgzyRtY3lJDnVTCA/r47bHnDI/hneNNawW5mItuHMn4VN4V+DSODJHyz9qWGsFR9VoqfMjSTsl9l8ID/VxIWgJCoNpktIzpZFLUuqwb8TyZgqUV3ibd1RAapDCi56ixfsM5wKcRKW8Q2JHhiEFmDbh//SpjLUs4Tf503Ve5zDNLGGozhBCIh5ER6tOmqPz3wmKfDfKB4+yFWrZmZTkXhpLKM49nKsda0LRtlUiCMyI1pjG3hKgvY+dg8PJ47Ya5c/Cuayd6xwyqjFbWmlf7AMMJhLXdbOP1Qyr4QTHTx1dXMTtkSrYSyUCD2MeXSMKuYUwFoQlQ9hAZUz3GI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
